server:
  port: 8080
logging:
  level:
    root: OFF
    org.springframework.web: OFF
    org.springframework.boot: OFF
    org.springframework.boot.autoconfigure: OFF
    ru.practicum.peoplenear: DEBUG
spring:
  jpa:
    show-sql:
      true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./db/people_db
    username: dbuser
    password: 12345
    driver-class-name: org.h2.Driver
  sql:
    init:
      #      почему то для H2 ликви не отрабатывает
      schema-locations: classpath:db/changelog/**/*.sql
  #      data-locations: classpath:data_local.sql
  liquibase:
    enabled: false