server:
  port: 8080
spring:
  sql:
    init:
      mode: always
  application:
    name: people-near
  datasource:
    url: jdbc:postgresql://localhost:5432/people_db
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.boot.autoconfigure: INFO