server:
  port: 8080
logging:
  level:
    root: OFF
    #    org.springframework.web: DEBUG
    #    org.springframework.boot: DEBUG
    org.hibernate.SQL: DEBUG
#    org.springframework.boot.autoconfigure: INFO
spring:
  datasource:
    url: jdbc:h2:file:./db/people_db
    username: dbuser
    password: 12345
    driver-class-name: org.h2.Driver
  sql:
    init:
      #      почему то для H2 ликви не отрабатывает
      schema-locations: classpath:db/changelog/**/*.sql
  #      data-locations: classpath:data_local.sql
  liquibase:
    enabled: false